name: Build Sinum pour Windows User

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # Permet aussi de le lancer manuellement si besoin

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Lancer le build natif Mac dans le dossier iOS
        run: |
          cd iOS
          chmod +x build-mac.sh
          ./build-mac.sh

      - name: Récupérer le fichier compilé
        uses: actions/upload-artifact@v4
        with:
          name: sinum-compilé
          path: iOS/
